// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqfBIwNb-NB0qbA_NZuN2guXNZglO7A5I',
    appId: '1:449282067643:web:8463a57662f5dc3df16d9e',
    messagingSenderId: '449282067643',
    projectId: 'pizza-delivery-f7b01',
    authDomain: 'pizza-delivery-f7b01.firebaseapp.com',
    storageBucket: 'pizza-delivery-f7b01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaddwIi3H2hEFfuRz4gFGAPzPgaAdn8kM',
    appId: '1:449282067643:android:15d69c45f6e5cfc6f16d9e',
    messagingSenderId: '449282067643',
    projectId: 'pizza-delivery-f7b01',
    storageBucket: 'pizza-delivery-f7b01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK2jTxbCIMB94dScZJPBrqS6NLu9dgk_g',
    appId: '1:449282067643:ios:a98969e6bf4ba1f2f16d9e',
    messagingSenderId: '449282067643',
    projectId: 'pizza-delivery-f7b01',
    storageBucket: 'pizza-delivery-f7b01.appspot.com',
    iosBundleId: 'com.example.flutterPizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK2jTxbCIMB94dScZJPBrqS6NLu9dgk_g',
    appId: '1:449282067643:ios:a98969e6bf4ba1f2f16d9e',
    messagingSenderId: '449282067643',
    projectId: 'pizza-delivery-f7b01',
    storageBucket: 'pizza-delivery-f7b01.appspot.com',
    iosBundleId: 'com.example.flutterPizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqfBIwNb-NB0qbA_NZuN2guXNZglO7A5I',
    appId: '1:449282067643:web:03de03b7c4bd11fdf16d9e',
    messagingSenderId: '449282067643',
    projectId: 'pizza-delivery-f7b01',
    authDomain: 'pizza-delivery-f7b01.firebaseapp.com',
    storageBucket: 'pizza-delivery-f7b01.appspot.com',
  );
}
